CREATE TABLE STUDENTS
(
    USER_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    STUDENT_ID BIGINT NOT NULL,
    FIRST_NAME VARCHAR(64) NOT NULL,
    LAST_NAME VARCHAR(64) NOT NULL,
    PASSWORD VARCHAR(64) NOT NULL,
    FACULTY VARCHAR(64) NOT NULL,
    BRANCH VARCHAR(64) NOT NULL,
    ACCOUNT_STATUS VARCHAR(24) DEFAULT 'active' NOT NULL,
    LAST_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (USER_ID));

CREATE TABLE TEACHERS
(
    USER_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    TEACHER_ID BIGINT NOT NULL,
    FIRST_NAME VARCHAR(64) NOT NULL,
    LAST_NAME VARCHAR(64) NOT NULL,
    PASSWORD VARCHAR(64) NOT NULL,
    FACULTY VARCHAR(64) NOT NULL,
    COURSE_NAME VARCHAR(64) NOT NULL,
    COURSE_ID VARCHAR(24) NOT NULL,
    ACCOUNT_STATUS VARCHAR(24) DEFAULT 'pending' NOT NULL,
    LAST_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (USER_ID));

CREATE TABLE QUIZ
(
    QUIZ_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    QUIZ_NAME VARCHAR(64) NOT NULL,
    QUIZ_COMMENTS VARCHAR(128) NOT NULL,
    QUIZ_STATUS VARCHAR(24) DEFAULT 'open' NOT NULL,
    TEACHER_ID BIGINT NOT NULL,
    COURSE_NAME VARCHAR(64) NOT NULL,
    COURSE_ID VARCHAR(24) NOT NULL,
    JOIN_CODE VARCHAR(12),
    COVER_IMAGES VARCHAR(128),
    START_DATE DATE NOT NULL,
    END_DATE DATE,
PRIMARY KEY (QUIZ_ID));

CREATE TABLE QUESTIONS
(
    QUESTION_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    QUESTION_NAME VARCHAR(64) NOT NULL,
    QUESTION_NUMBER VARCHAR(24) NOT NULL,
    QUESTION_PICTURE VARCHAR(128),
    QUIZ_ID INTEGER NOT NULL,
PRIMARY KEY (QUESTION_ID));

CREATE TABLE CHOICES
(
    CHOICE_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    CHOICE_NAME VARCHAR(128) NOT NULL,
    CHOICE_CORRECT BOOLEAN DEFAULT false NOT NULL,
    QUESTION_ID INTEGER NOT NULL,
PRIMARY KEY (CHOICE_ID));