
DROP TABLE students;
DROP TABLE teachers;
DROP TABLE choices;
DROP TABLE quiz;
DROP TABLE questions;

CREATE TABLE STUDENTS
(
    STUDENT_ID BIGINT NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    FACULTY_ID VARCHAR(255) NOT NULL,
    BRANCH_ID VARCHAR(255) NOT NULL,
    ACCOUNT_STATUS VARCHAR(24) DEFAULT 'active' NOT NULL,
    LAST_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (STUDENT_ID));

CREATE TABLE TEACHERS
(
    TEACHER_ID BIGINT NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    FACULTY_ID VARCHAR(255) NOT NULL,
    COURSE_NAME VARCHAR(255) NOT NULL,
    COURSE_ID VARCHAR(24) NOT NULL,
    ACCOUNT_STATUS VARCHAR(24) DEFAULT 'pending' NOT NULL,
    LAST_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (TEACHER_ID));

CREATE TABLE BRANCH 
(
    BRANCH_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    BRANCH_NAME VARCHAR(128) NOT NULL,
    FACULTY_ID INTEGER NOT NULL,
    PRIMARY KEY (BRANCH_ID));
);

CREATE TABLE FACULTY 
(
    FACULTY_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    FACULTY_NAME VARCHAR(128) NOT NULL,
    PRIMARY KEY (FACULTY_ID));
);

CREATE TABLE QUIZ
(
    QUIZ_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    QUIZ_NAME VARCHAR(255) NOT NULL,
    QUIZ_COMMENTS VARCHAR(128) NOT NULL,
    QUIZ_STATUS VARCHAR(24) DEFAULT 'open' NOT NULL,
    TEACHER_ID BIGINT NOT NULL,
    COURSE_NAME VARCHAR(255) NOT NULL,
    COURSE_ID VARCHAR(24) NOT NULL,
    JOIN_CODE VARCHAR(12),
    COVER_IMAGES VARCHAR(128),
    START_DATE DATE NOT NULL,
    END_DATE DATE,
PRIMARY KEY (QUIZ_ID));

CREATE TABLE QUESTIONS
(
    QUESTION_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    QUESTION_NAME VARCHAR(255) NOT NULL,
    QUESTION_NUMBER VARCHAR(24) NOT NULL,
    QUESTION_PICTURE VARCHAR(128),
    QUIZ_ID INTEGER NOT NULL,
PRIMARY KEY (QUESTION_ID));

CREATE TABLE CHOICES
(
    CHOICE_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    CHOICE_NAME VARCHAR(128) NOT NULL,
    CHOICE_CORRECT BOOLEAN DEFAULT false NOT NULL,
    QUESTION_ID INTEGER NOT NULL,
PRIMARY KEY (CHOICE_ID));